CREATE DATABASE QUANLYKHACHSAN
GO
USE QUANLYKHACHSAN
GO

-- Tạo các bảng
-- Các bảng độc lập (không có khóa ngoại)
CREATE TABLE KHUVUC (
    MaKV VARCHAR(50) PRIMARY KEY,
    TenKhuVuc NVARCHAR(100),
    DiaChi NVARCHAR(255)
);

CREATE TABLE LOAIPHONG (
    MaLoai VARCHAR(50) PRIMARY KEY,
    TenLoai NVARCHAR(100)
);

CREATE TABLE THIETBI (
    MaThietBi VARCHAR(50) PRIMARY KEY,
    TenThietBi NVARCHAR(100),
    GiaTienBoiThuong DECIMAL(18, 2)
);

CREATE TABLE NHANVIEN (
    MaNV VARCHAR(50) PRIMARY KEY,
    TenNV NVARCHAR(100)
);

CREATE TABLE NHOMTHUE (
    MaNhom VARCHAR(50) PRIMARY KEY,
    MaKHDaiDien VARCHAR(50) NULL -- Gắn foreign key sau
);

-- 3 loại nhân viên
CREATE TABLE NV_KDOANH (
    MaNV VARCHAR(50) PRIMARY KEY,
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE NV_QLY (
    MaNV VARCHAR(50) PRIMARY KEY,
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE NV_KTOAN (
    MaNV VARCHAR(50) PRIMARY KEY,
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);

-- Các bảng có khóa ngoại
CREATE TABLE KHACHHANG (
    MaKH VARCHAR(50) PRIMARY KEY,
    HoTen NVARCHAR(100),
    SDT VARCHAR(20),
    Email VARCHAR(100),
    GioiTinh NVARCHAR(10),
    CCCD VARCHAR(20)
);

-- Thêm khóa ngoại "Đại diện" cho NHOMTHUE sau khi đã có KHACHHANG
ALTER TABLE NHOMTHUE
ADD CONSTRAINT FK_NhomThue_KhachHang FOREIGN KEY (MaKHDaiDien) REFERENCES KHACHHANG(MaKH);

CREATE TABLE CHITIET_NHOMTHUE (
    MaNhom VARCHAR(50),
    MaKH VARCHAR(50),
    PRIMARY KEY (MaNhom, MaKH),
    FOREIGN KEY (MaNhom) REFERENCES NHOMTHUE(MaNhom),
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
);

CREATE TABLE PHONG (
    MaPhong VARCHAR(50) PRIMARY KEY,
    SoNguoiThueToiDa INT,
    GiaThuePhong DECIMAL(18, 2),
    TrangThai NVARCHAR(50),
    DieuKienChoThue NVARCHAR(255),
    MaKV VARCHAR(50),
    MaLoai VARCHAR(50),
    FOREIGN KEY (MaKV) REFERENCES KHUVUC(MaKV),
    FOREIGN KEY (MaLoai) REFERENCES LOAIPHONG(MaLoai)
);

CREATE TABLE PHIEUYEUCAU (
    MaPhieuYC VARCHAR(50) PRIMARY KEY,
    SoNguoiDuKien INT,
    KhoangGia DECIMAL(18, 2),
    ThoiGianDuKien NVARCHAR(100),
    GhiChu NVARCHAR(255),
    HinhThucThue NVARCHAR(100),
    MaKH VARCHAR(50),
    MaKV VARCHAR(50) NULL,
    MaLoai VARCHAR(50) NULL,
    MaPhong VARCHAR(50) NULL,
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    FOREIGN KEY (MaKV) REFERENCES KHUVUC(MaKV),
    FOREIGN KEY (MaLoai) REFERENCES LOAIPHONG(MaLoai),
    FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong)
);

CREATE TABLE LICHHEN (
    MaLH VARCHAR(50) PRIMARY KEY,
    ThoiGian DATETIME,
    LyDo NVARCHAR(255),
    MaPhieuYC VARCHAR(50),
    MaNV VARCHAR(50),
    FOREIGN KEY (MaPhieuYC) REFERENCES PHIEUYEUCAU(MaPhieuYC),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)

);

CREATE TABLE GIUONG (
    MaGiuong VARCHAR(50) PRIMARY KEY,
    GiaThue DECIMAL(18, 2),
    TrangThai NVARCHAR(50),
    MaPhong VARCHAR(50),
    FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong)
);

CREATE TABLE PHIEUDATCOC (
    MaPhieuDatCoc VARCHAR(50) PRIMARY KEY,
    NgayLap DATE,
    LoaiDatCoc NVARCHAR(100),
    TrangThai NVARCHAR(50), --Da thanh toan, Chua thanh toan, ...
    TienCoc DECIMAL(18, 2),
    MaKH VARCHAR(50),
    MaNV VARCHAR(50),
    MaPhong VARCHAR(50),
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    FOREIGN KEY (MaNV) REFERENCES NV_KDOANH(MaNV),
    FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong)
);

CREATE TABLE CHITIETDATCOC (
    MaPhieuDatCoc VARCHAR(50),
    MaGiuong VARCHAR(50),
    PRIMARY KEY (MaPhieuDatCoc, MaGiuong),
    FOREIGN KEY (MaPhieuDatCoc) REFERENCES PHIEUDATCOC(MaPhieuDatCoc),
    FOREIGN KEY (MaGiuong) REFERENCES GIUONG(MaGiuong)
);

CREATE TABLE HOPDONG (
    MaHopDong VARCHAR(50) PRIMARY KEY,
    NgayKy DATE,
    NgayBatDau DATE,
    NgayKetThuc DATE,
	NoiDungHD NVARCHAR(500),
    MaPhieuDatCoc VARCHAR(50),
    MaNV VARCHAR(50),
    FOREIGN KEY (MaPhieuDatCoc) REFERENCES PHIEUDATCOC(MaPhieuDatCoc),
    FOREIGN KEY (MaNV) REFERENCES NV_KDOANH(MaNV)
);

CREATE TABLE PHIEUTRAPHONG (
    MaPhieuTra VARCHAR(50) PRIMARY KEY,
    NgayTraPhong DATE,
    TinhTrangHD NVARCHAR(100),
    MaPhieuDatCoc VARCHAR(50),
    MaNV VARCHAR(50),
    FOREIGN KEY (MaPhieuDatCoc) REFERENCES PHIEUDATCOC(MaPhieuDatCoc),
    FOREIGN KEY (MaNV) REFERENCES NV_KDOANH(MaNV)
);

CREATE TABLE PHIEUKIEMTRA (
    MaPhieuKiemTra VARCHAR(50) PRIMARY KEY,
    SoDienDung FLOAT,
    SoNuocDung FLOAT,
    MaPhieuTra VARCHAR(50),
    MaNV VARCHAR(50),
    FOREIGN KEY (MaPhieuTra) REFERENCES PHIEUTRAPHONG(MaPhieuTra),
    FOREIGN KEY (MaNV) REFERENCES NV_QLY(MaNV)
);

CREATE TABLE CHITIETKIEMTRA (
    MaPhieuKiemTra VARCHAR(50),
    MaThietBi VARCHAR(50),
    SoLuongHuHong INT,
    PRIMARY KEY (MaPhieuKiemTra, MaThietBi),
    FOREIGN KEY (MaPhieuKiemTra) REFERENCES PHIEUKIEMTRA(MaPhieuKiemTra),
    FOREIGN KEY (MaThietBi) REFERENCES THIETBI(MaThietBi)
);

CREATE TABLE BIENBAN (
    MaBienBan VARCHAR(50) PRIMARY KEY,
    NgayLap DATE,
    MaHopDong VARCHAR(50),
    MaNV VARCHAR(50),
    FOREIGN KEY (MaHopDong) REFERENCES HOPDONG(MaHopDong),
    FOREIGN KEY (MaNV) REFERENCES NV_QLY(MaNV)
);

CREATE TABLE BIENBAN_THIETBI (
    MaBienBan VARCHAR(50),
    MaThietBi VARCHAR(50),
    SoLuong INT,
    PRIMARY KEY (MaBienBan, MaThietBi),
    FOREIGN KEY (MaBienBan) REFERENCES BIENBAN(MaBienBan),
    FOREIGN KEY (MaThietBi) REFERENCES THIETBI(MaThietBi)
);

CREATE TABLE HOADON (
    MaHD VARCHAR(50) PRIMARY KEY,
    LoaiHoaDon NVARCHAR(50),
    SoTien DECIMAL(18, 2),
    NgayThanhToan DATE,
    MaPhieuTra VARCHAR(50),
    FOREIGN KEY (MaPhieuTra) REFERENCES PHIEUTRAPHONG(MaPhieuTra)
);

CREATE TABLE BANGDOISOAT (
    MaBang VARCHAR(50) PRIMARY KEY,
    TyLeHoanCoc FLOAT,
    SoTienHoanCoc DECIMAL(18, 2),
    TongKhauTru DECIMAL(18, 2),
    MaPhieuTra VARCHAR(50),
    FOREIGN KEY (MaPhieuTra) REFERENCES PHIEUTRAPHONG(MaPhieuTra)
);

CREATE TABLE CHITIETKHAUTRU (
    MaKhauTru VARCHAR(50) PRIMARY KEY,
    TenKhoan NVARCHAR(100),
    SoTien DECIMAL(18, 2),
    MaBang VARCHAR(50),
    FOREIGN KEY (MaBang) REFERENCES BANGDOISOAT(MaBang)
);