USE QUANLYKHACHSAN
GO
CREATE OR ALTER PROCEDURE sp_GetAllDepositPaid
AS
BEGIN
    SELECT 
        P.MaPhieuDatCoc, 
        K.HoTen, 
        P.NgayLap, 
        CN.MaNhom
    FROM PHIEUDATCOC P
    JOIN KHACHHANG K ON K.MaKH = P.MaKH
    LEFT JOIN CHITIET_NHOMTHUE CN ON CN.MaKH = K.MaKH
    WHERE P.TrangThai = N'Đã thanh toán' AND 
	P.MaPhieuDatCoc NOT IN (SELECT MaPhieuDatCoc FROM HOPDONG WHERE MaPhieuDatCoc IS NOT NULL)
END
GO
EXEC sp_GetAllDepositPaid;

GO
CREATE OR ALTER PROCEDURE sp_DuyetDatCoc
	@maPhieu VARCHAR(50)
AS	
BEGIN
	UPDATE PHIEUDATCOC
	SET TrangThai = N'Được chấp thuận'
	WHERE MaPhieuDatCoc = @maPhieu
END

GO
CREATE OR ALTER PROCEDURE sp_TuChoiDatCoc
	@maPhieu VARCHAR(50)
AS	
BEGIN
	UPDATE PHIEUDATCOC
	SET TrangThai = N'Không được chấp thuận'
	WHERE MaPhieuDatCoc = @maPhieu
END

GO
CREATE OR ALTER PROCEDURE LayDSDatCocDuocDuyet
AS
BEGIN
	SELECT MaPhieuDatCoc, HoTen, NgayLap, MaNhom
	FROM PHIEUDATCOC
	JOIN KHACHHANG ON KHACHHANG.MaKH = PHIEUDATCOC.MaKH
	LEFT JOIN CHITIET_NHOMTHUE ON CHITIET_NHOMTHUE.MAKH = KHACHHANG.MaKH
	WHERE TrangThai = N'Được chấp thuận' AND MaPhieuDatCoc NOT IN (
		SELECT MaPhieuDatCoc FROM HOPDONG
	)	
END

GO
CREATE OR ALTER PROCEDURE LapHopDong
    @MaPhieu VARCHAR(50),
    @NgayBatDau DATE,
    @NgayKetThuc DATE,
    @NoiDungHD NVARCHAR(500),
    @MaNV VARCHAR(50) = NULL -- Defaulted to NULL
AS
BEGIN
    DECLARE @MaHD VARCHAR(50);
    DECLARE @NgayKy DATE;
    DECLARE @NextNum INT;

    -- 1. Find the highest current number for ID generation
    SELECT @NextNum = ISNULL(MAX(CAST(SUBSTRING(MaHopDong, 3, 10) AS INT)), 0) + 1
    FROM HOPDONG;

    -- 2. Format the new ID (HD001, HD002...)
    SET @MaHD = 'HD' + RIGHT('000' + CAST(@NextNum AS VARCHAR(10)), 3);
    SET @NgayKy = CAST(GETDATE() AS DATE);

    -- 3. Insert the new record including @MaNV
    INSERT INTO HOPDONG (MaHopDong, NgayKy, NgayBatDau, NgayKetThuc, NoiDungHD, MaPhieuDatCoc, MaNV)
    VALUES (@MaHD, @NgayKy, @NgayBatDau, @NgayKetThuc, @NoiDungHD, @MaPhieu, @MaNV);
    -- 3. Return the ID for Node.js to capture
    SELECT @MaHD AS MaHopDong;
END;

GO
CREATE OR ALTER PROCEDURE LayDSHopDong
AS
BEGIN
	SELECT MaHopDong, NgayKy, HoTen
	FROM HOPDONG
	JOIN PHIEUDATCOC ON HOPDONG.MaPhieuDatCoc = PHIEUDATCOC.MaPhieuDatCoc
	JOIN KHACHHANG ON PHIEUDATCOC.MaKH = KHACHHANG.MaKH
END;

GO
CREATE OR ALTER PROCEDURE LapBienBan
    @MaHD VARCHAR(50),
    @MaNV VARCHAR(50) = NULL -- Defaulted to NULL
AS
BEGIN
    DECLARE @MaBB VARCHAR(50);
    DECLARE @NgayLap DATE;
    DECLARE @NextNum INT;
    DECLARE @validateBB VARCHAR(50);

    -- Check if a record already exists for this contract
    SET @validateBB = (SELECT MaBienBan FROM BIENBAN WHERE MaHopDong = @MaHD);
    IF (@validateBB IS NOT NULL)
        RETURN;

    -- 1. Generate the ID (BB001, BB002...)
    SELECT @NextNum = ISNULL(MAX(CAST(SUBSTRING(MaBienBan, 3, 10) AS INT)), 0) + 1
    FROM BIENBAN;

    SET @MaBB = 'BB' + RIGHT('000' + CAST(@NextNum AS VARCHAR(10)), 3);
    SET @NgayLap = CAST(GETDATE() AS DATE);

    -- 2. Insert the new record including @MaNV
    INSERT INTO BIENBAN (MaBienBan, NgayLap, MaHopDong, MaNV)
    VALUES (@MaBB, @NgayLap, @MaHD, @MaNV);
END;

GO
CREATE OR ALTER PROCEDURE DisplayChiTietBienBan
	@MaHD VARCHAR(50)
AS
BEGIN
    DECLARE @MaBB VARCHAR(50);
    
	SET @MaBB = (SELECT MaBienBan FROM BIENBAN WHERE MaHopDong = @MaHD)

	IF (@MaBB IS NULL)
		RETURN;
	SELECT BIENBAN_THIETBI.MaThietBi, THIETBI.TenThietBi, BIENBAN_THIETBI.SoLuong
	FROM BIENBAN_THIETBI
	JOIN THIETBI ON THIETBI.MaThietBi = BIENBAN_THIETBI.MaThietBi
	WHERE MaBienBan = @MaBB
END;

GO
CREATE OR ALTER PROCEDURE LayDSThietBi
AS
BEGIN
	SELECT THIETBI.MaThietBi, THIETBI.TenThietBi
	FROM THIETBI
END


GO
CREATE OR ALTER PROCEDURE ThemChiTietBienBan
	@MaHD VARCHAR(50),
	@MaTB VARCHAR(50),
	@SoLuong INT
AS
BEGIN
    DECLARE @MaBB VARCHAR(50);
    
	SET @MaBB = (SELECT MaBienBan FROM BIENBAN WHERE MaHopDong = @MaHD)

	IF (@MaBB IS NULL)
		RETURN;
	
	IF (@SoLuong < 0)
		RETURN;
	IF EXISTS (SELECT * FROM BIENBAN_THIETBI WHERE MaBienBan = @MaBB AND MaThietBi = @MaTB)
		RETURN;

	INSERT INTO BIENBAN_THIETBI (MaBienBan, MaThietBi, SoLuong) VALUES (@MaBB, @MaTB, @SoLuong)
END;

GO
CREATE OR ALTER PROCEDURE XoaChiTietBienBan
	@MaHD VARCHAR(50),
	@MaTB VARCHAR(50)
AS
BEGIN
    DECLARE @MaBB VARCHAR(50);
    
	SET @MaBB = (SELECT MaBienBan FROM BIENBAN WHERE MaHopDong = @MaHD)

	IF (@MaBB IS NULL)
		RETURN;
	
	DELETE FROM BIENBAN_THIETBI WHERE MaBienBan = @MaBB  AND MaThietBi = @MaTB;	
END;
GO
CREATE OR ALTER PROCEDURE XoaBienBan
	@MaHD VARCHAR(50)
AS
BEGIN
    DECLARE @MaBB VARCHAR(50);
    
	SET @MaBB = (SELECT MaBienBan FROM BIENBAN WHERE MaHopDong = @MaHD);

	IF (@MaBB IS NULL)
		RETURN;
	
	DELETE FROM BIENBAN_THIETBI WHERE MaBienBan = @MaBB;
	DELETE FROM BIENBAN WHERE MaHopDong = @MaHD;
END;


-- INSERT INTO PHIEUDATCOC (MaPhieuDatCoc, NgayLap, LoaiDatCoc, TrangThai, TienCoc, MaKH, MaNV) VALUES ('PDC1000', '2025-02-12', N'Cọc giữ chỗ', N'Đã thanh toán', 3500000, 'KH099', 'NV005');
-- SELECT * FROM PHIEUDATCOC WHERE MaPhieuDatCoc = 'PDC1000'
-- Exec LayDSThietBi
-- SELECT * FROM BIENBAN
-- SELECT * FROM  BIENBAN_THIETBI
-- DELETE FROM BIENBAN_THIETBI
-- DELETE FROM BIENBAN
-- select * from NV_QLY
-- SELECT * FROM NHANVIEN